-- Execute este SQL uma única vez no Supabase > SQL Editor.

create table if not exists public.site_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_name text not null check (event_name in ('visit','amazon_click')),
  button_name text,
  page_path text,
  referrer text
);

alter table public.site_events enable row level security;

-- Visitantes anônimos podem apenas GRAVAR eventos.
drop policy if exists "anonymous can insert events" on public.site_events;
create policy "anonymous can insert events"
on public.site_events
for insert
to anon
with check (true);

-- Somente usuários autenticados do Supabase podem LER as estatísticas.
drop policy if exists "authenticated can read events" on public.site_events;
create policy "authenticated can read events"
on public.site_events
for select
to authenticated
using (true);

-- Não concedemos update/delete aos visitantes.
